### ISSUE TITLE
Importing Procedure

### ISSUE THREAD

**Issue by CptnKoogers** [RichysHub/MagicaVoxel-VOX-importer#17]
You're project seems really interesting for it's material physics based import!

I copied the script into the text editor of blender and ran it but it's unclear how it works. Can someone clarify the procedure for importing a file after properly exporting to the vox (old format) in magica voxel?

**Comment by RichysHub** [comment]
Hello CptnKoogers, thank you for getting in contact.

This importer is intended to be used as an add-on, and installed within Blender, rather than being run as a script from the text editor.

Per this issue, I have updated [the readme](https://github.com/RichysHub/MagicaVoxel-VOX-importer/blob/master/README.md) with installation and usage instructions. 

Hopefully these help you get this add-on working, and happy voxelling. 👍
